// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-r_3nnmH49BNVZDv_3biCqvygdcW4Hq8',
    appId: '1:952371122223:web:cf03441c8afb950da1b6da',
    messagingSenderId: '952371122223',
    projectId: 'flutternotification-41667',
    authDomain: 'flutternotification-41667.firebaseapp.com',
    storageBucket: 'flutternotification-41667.appspot.com',
    measurementId: 'G-98B994M0M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkxueUfPXcL0zhHT_halaSuA8QvQAwu0',
    appId: '1:952371122223:android:f92cabbd42e25d37a1b6da',
    messagingSenderId: '952371122223',
    projectId: 'flutternotification-41667',
    storageBucket: 'flutternotification-41667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeJBLxEmyKoonCb3s2-MCe0m88s3fEX4',
    appId: '1:952371122223:ios:5352e03a06eb0e91a1b6da',
    messagingSenderId: '952371122223',
    projectId: 'flutternotification-41667',
    storageBucket: 'flutternotification-41667.appspot.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGeJBLxEmyKoonCb3s2-MCe0m88s3fEX4',
    appId: '1:952371122223:ios:5352e03a06eb0e91a1b6da',
    messagingSenderId: '952371122223',
    projectId: 'flutternotification-41667',
    storageBucket: 'flutternotification-41667.appspot.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-r_3nnmH49BNVZDv_3biCqvygdcW4Hq8',
    appId: '1:952371122223:web:c42c52ed7ed2e8aba1b6da',
    messagingSenderId: '952371122223',
    projectId: 'flutternotification-41667',
    authDomain: 'flutternotification-41667.firebaseapp.com',
    storageBucket: 'flutternotification-41667.appspot.com',
    measurementId: 'G-HP1XL4RWY6',
  );
}
